### ISSUE TITLE
Make article extractor with with dn.se

### ISSUE THREAD

**Issue by RyuTribal** [RyuTribal/news_scraper#19]
Problem with dn is that it's rss urls goes as following "dn.se/rss/om/fotboll" which doesn't work with our attempt at putting /rss, /feed, /feeds after a certain url. Make an exception in **source.py** in function **set_feeds**.

**Comment by lodenrogue** [comment]
I could be wrong but it seems dn.se/rss/om/fotboll is just a subset of the items in dn.se/rss. If this is correct do you need the subset or can you work with the bigger set?

**Comment by SuadHus** [comment]
> I could be wrong but it seems dn.se/rss/om/fotboll is just a subset of the items in dn.se/rss. If this is correct do you need the subset or can you work with the bigger set?

yes you are correct!
